### ISSUE TITLE
api 문서 재 검토

### ISSUE THREAD

**Issue by rnjshippo** [boostcamp-2020/IssueTracker-19#32]
### WIKI
https://github.com/boostcamp-2020/IssueTracker-19/wiki/API-%EB%AC%B8%EC%84%9C-%EC%88%98%EC%A0%95%EB%B3%B8-10.28

### HackMD
https://hackmd.io/3Ou-ZrZBQ_-EF7CwqDxUVw

**Comment by Front-line-dev** [comment]
뭐가 문제인지 모르고 있다가 [토스트 RESTful 문서](https://meetup.toast.com/posts/92)를 보고 RESTful이 이런거구나 알게되었습니다 `GET : /users/{userid}/devices (일반적으로 소유 ‘has’의 관계를 표현할 때)` 중간에 넣는게 이상하다고 생각했는데 이 방법이 정석이네요

**Comment by rnjshippo** [comment]
설명드리려고 했는데 이미 이해하셨군요 👍
