### ISSUE TITLE
getIssue API 관련 이슈

### ISSUE THREAD

**Issue by Front-line-dev** [boostcamp-2020/IssueTracker-19#68]
# 이슈 생성 이유

## 1. API 문서와 실제 데이터가 다름

API 문서에 적혀져 있는 내용
```
issues: [
        {
            no: number,
            title: string,
            author: string,
            assignees: [user],
            labels: [label],
            isOpened: boolean,
            createdAt: datetime,
            closedAt: datetime | null,
            milestone: milestone | null, <- 실제로는 milestoneTitle 값이 들어가 있음
            commentCount: number

            comments: [comment] <- API 문서에 없으나 실제로는 들어가 있음
        }
    ]
```

코드쪽을 고쳐야 할 것 같습니다. 제가 생각해 봤을 때 이런식으로 고치면 좋을 것 같습니다

---
issue.model에서 getIssueList 함수에서 milestoneTitle --> miletoneNo

issue.model에서 getIssueList 함수에서 commentCount 값 추가

issue.model에서 getIssuesLableList 함수에서 조인 삭제

issue.model에서 getIssuesAssigneeList 함수에서 조인 삭제

user.model에서 getUsersProfile 함수 새로 작성 후 사용
```
getUsersProfile() {
    const sql = 'SELECT (no, nickname, image) FROM user;';
    return pool.execute(sql, [id]);
  },
```
label.model에서 getLabels 함수 사용

milestone.model에서 getMilestoneList 함수 사용

## 2. 서비스로 옮기기 위한 함수 쪼개기 (리팩토링)

그 후, js map을 이용해서 각 데이터들에 대한 hashMap을 생성

```
예시
const labelMap = new Map(labels.map(label => [label.no, label]));
const userProfileMap = new Map(
  userProfileList.map(userProfile => [userProfile.no, userProfile]),
);
const assigneeMap = new Map(
  assigneeList.map(assignee => [assignee.no, userProfileMap.get(assignee.userNo)]),
);
```

**Comment by rnjshippo** [comment]
주말에 코딩을 안해서 이제야 확인했네요. ㅠ

일단 언급하신 내용에 대한 제 생각을 말씀드려볼게요.

### 1. 
```
- issue.model에서 getIssueList 함수에서 milestoneTitle --> miletoneNo
```

지금 milestone에 no가 아니라 title이 들어가고 있기는 합니다!

그런데 저번에 API 회의할 때, 프론트에서 검색하는 화면에서 no로 보이는 것보다 title로 보이는게 낫지 않냐고 하셔서 title로 하기로 했던거로 기억해서요. 그래서 프론트에 줄 때도 title로 내려주고, 필터링할 때도 title로 하도록 구현해놓은 상태입니다! 

### 2. 
```
- issue.model에서 getIssueList 함수에서 commentCount 값 추가
- comments: [comment] <- API 문서에 없으나 실제로는 들어가 있음
```

comments 속성이 내려줄 때 필요없는 정보이기는 해요. 그런데 저게 필터링 로직에서 사용하기 위해서 넣어놓은 값이에요. 저 comments 배열이 있어야 해당 이슈에 내가 쓴 댓글이 있는지 필터링하는 부분이 동작을 합니다! ~~물론 필터링 다 끝내고 res하기 전에 comments 속성만 다 삭제해주고 내려줘도 되지만, 그렇게 하려면 불필요하게 한번 더 순회해야 해서 그냥 놔둔상태입니다. ㅠ~~ 
-> 이 부분은 착각했네요 comments는 안내려주도록 변경할게요!

그리고 comments 배열을 생성하는 동시에 각 이슈에 comment가 몇개 있는지 확인도 가능하기 때문에, issue.model의 getIssueList 함수의 쿼리에서 commentCount를 체크하는 부분을 제외시켰습니다. 이미 commentCount값을 알기 때문에 쿼리에 그렇게 쓰지 않아도 되는 것도 있고, 쿼리를 그렇게 작성하면 모든 이슈마다 select 구문을 수행해야해서 시간 소모가 큰 것도 있어서요.


### 3. 
```
- issue.model에서 getIssuesLableList 함수에서 조인 삭제
- issue.model에서 getIssuesAssigneeList 함수에서 조인 삭제
- user.model에서 getUsersProfile 함수 새로 작성 후 사용
```
 
이 부분은 미완성 코드라서 아직 어떤 코드인지 확실히는 모르겠지만.. 제가 이해한 내용을 토대로 커밋하신 코드에 리뷰 넣어놨으니 확인해주시면 좋을 것 같습니다!

그리고 내일 직접 구현 방향에 대한 설명을 해주시면 감사하겠습니다~ 😀

**Comment by rnjshippo** [comment]
그리고 추가로 기존 코드 리팩토링 진행해봤습니다. 

필터링 로직과 issues 가져오는 부분을 issue.service 로 분리해서 controller 내에서는 서비스만 호출하도록 변경했습니다. 

아래 커밋 참고하시면 좋을 것 같습니다.

- [refactor] 이슈 필터링을 service로 분리 856142b
- [fix] 클로저 안의 변수 위치 변경 21284a6

=> 이번 리팩토링은 기존과 로직은 동일합니다. 혹시 로직 전체를 바꾸고 싶다면 해당 부분을 전부 변경해도 괜찮습니다~ 😀
